ARDUINO_LIBS = IRremote
BOARD_TAG = feather32u4
MONITOR_PORT = /dev/cu.usb*
ARDMK_VENDOR      = archlinux-arduino
ALTERNATE_CORE = adafruit
ALTERNATE_CORE_PATH = /home/wayne/.arduino15/packages/adafruit/hardware/avr/1.4.15
include /usr/share/arduino/Arduino.mk